import 'package:flutter/material.dart';
import '../widgets/element_cell.dart';
import '../widgets/element_cell_list.dart';
import '../models/element.dart';
import '../models/element_category.dart';

List<dynamic> elementList = const [
  ChemicalElement('Hidrogênio', 1, 1, ElementCategory.nonmetal),
  ChemicalElement('Hélio', 1, 18, ElementCategory.nonmetal),
  ChemicalElement('Lítio', 2, 1, ElementCategory.metal),
  ChemicalElement('Berílio', 2, 2, ElementCategory.metal),
  ChemicalElement('Boro', 2, 13, ElementCategory.semimetal),
  ChemicalElement('Carbono', 2, 14, ElementCategory.nonmetal),
  ChemicalElement('Nitrogênio', 2, 15, ElementCategory.nonmetal),
  ChemicalElement('Oxigênio', 2, 16, ElementCategory.nonmetal),
  ChemicalElement('Flúor', 2, 17, ElementCategory.nonmetal),
  ChemicalElement('Neônio', 2, 18, ElementCategory.nonmetal),
  ChemicalElement('Sódio', 3, 1, ElementCategory.metal),
  ChemicalElement('Magnésio', 3, 2, ElementCategory.metal),
  ChemicalElement('Alumínio', 3, 13, ElementCategory.metal),
  ChemicalElement('Silício', 3, 14, ElementCategory.semimetal),
  ChemicalElement('Fósforo', 3, 15, ElementCategory.nonmetal),
  ChemicalElement('Enxofre', 3, 16, ElementCategory.nonmetal),
  ChemicalElement('Cloro', 3, 17, ElementCategory.nonmetal),
  ChemicalElement('Argônio', 3, 18, ElementCategory.nonmetal),
  ChemicalElement('Potássio', 4, 1, ElementCategory.metal),
  ChemicalElement('Cálcio', 4, 2, ElementCategory.metal),
  ChemicalElement('Escândio', 4, 3, ElementCategory.metal),
  ChemicalElement('Titânio', 4, 4, ElementCategory.metal),
  ChemicalElement('Vanádio', 4, 5, ElementCategory.metal),
  ChemicalElement('Cromo', 4, 6, ElementCategory.metal),
  ChemicalElement('Manganês', 4, 7, ElementCategory.metal),
  ChemicalElement('Ferro', 4, 8, ElementCategory.metal),
  ChemicalElement('Cobalto', 4, 9, ElementCategory.metal),
  ChemicalElement('Níquel', 4, 10, ElementCategory.metal),
  ChemicalElement('Cobre', 4, 11, ElementCategory.metal),
  ChemicalElement('Zinco', 4, 12, ElementCategory.metal),
  ChemicalElement('Gálio', 4, 13, ElementCategory.metal),
  ChemicalElement('Germânio', 4, 14, ElementCategory.semimetal),
  ChemicalElement('Arsênio', 4, 15, ElementCategory.semimetal),
  ChemicalElement('Selênio', 4, 16, ElementCategory.nonmetal),
  ChemicalElement('Bromo', 4, 17, ElementCategory.nonmetal),
  ChemicalElement('Criptônio', 4, 18, ElementCategory.nonmetal),
  ChemicalElement('Rubídio', 5, 1, ElementCategory.metal),
  ChemicalElement('Estrôncio', 5, 2, ElementCategory.metal),
  ChemicalElement('Ítrio', 5, 3, ElementCategory.metal),
  ChemicalElement('Zircônio', 5, 4, ElementCategory.metal),
  ChemicalElement('Nióbio', 5, 5, ElementCategory.metal),
  ChemicalElement('Molibdênio', 5, 6, ElementCategory.metal),
  ChemicalElement('Tecnécio', 5, 7, ElementCategory.metal),
  ChemicalElement('Rutênio', 5, 8, ElementCategory.metal),
  ChemicalElement('Ródio', 5, 9, ElementCategory.metal),
  ChemicalElement('Paládio', 5, 10, ElementCategory.metal),
  ChemicalElement('Prata', 5, 11, ElementCategory.metal),
  ChemicalElement('Cádmio', 5, 12, ElementCategory.metal),
  ChemicalElement('Índio', 5, 13, ElementCategory.metal),
  ChemicalElement('Estanho', 5, 14, ElementCategory.metal),
  ChemicalElement('Antimônio', 5, 15, ElementCategory.semimetal),
  ChemicalElement('Telúrio', 5, 16, ElementCategory.semimetal),
  ChemicalElement('Iodo', 5, 17, ElementCategory.nonmetal),
  ChemicalElement('Xenônio', 5, 18, ElementCategory.nonmetal),
  ChemicalElement('Césio', 6, 1, ElementCategory.metal),
  ChemicalElement('Bário', 6, 2, ElementCategory.metal),
  [
    ChemicalElement('Lantânio', 6, 3, ElementCategory.metal),
    ChemicalElement('Cério', 6, 4, ElementCategory.metal),
    ChemicalElement('Praseodímio', 6, 5, ElementCategory.metal),
    ChemicalElement('Neodímio', 6, 6, ElementCategory.metal),
    ChemicalElement('Promécio', 6, 7, ElementCategory.metal),
    ChemicalElement('Samário', 6, 8, ElementCategory.metal),
    ChemicalElement('Európio', 6, 9, ElementCategory.metal),
    ChemicalElement('Gadolínio', 6, 10, ElementCategory.metal),
    ChemicalElement('Térbio', 6, 11, ElementCategory.metal),
    ChemicalElement('Disprósio', 6, 12, ElementCategory.metal),
    ChemicalElement('Hólmio', 6, 13, ElementCategory.metal),
    ChemicalElement('Érbio', 6, 14, ElementCategory.metal),
    ChemicalElement('Túlio', 6, 15, ElementCategory.metal),
    ChemicalElement('Itérbio', 6, 16, ElementCategory.metal),
    ChemicalElement('Lutécio', 6, 17, ElementCategory.metal)
  ],
  ChemicalElement('Háfnio', 6, 4, ElementCategory.metal),
  ChemicalElement('Tântalo', 6, 5, ElementCategory.metal),
  ChemicalElement('Tungstênio', 6, 6, ElementCategory.metal),
  ChemicalElement('Rênio', 6, 7, ElementCategory.metal),
  ChemicalElement('Ósmio', 6, 8, ElementCategory.metal),
  ChemicalElement('Irídio', 6, 9, ElementCategory.metal),
  ChemicalElement('Platina', 6, 10, ElementCategory.metal),
  ChemicalElement('Ouro', 6, 11, ElementCategory.metal),
  ChemicalElement('Mercúrio', 6, 12, ElementCategory.metal),
  ChemicalElement('Tálio', 6, 13, ElementCategory.metal),
  ChemicalElement('Bismuto', 6, 15, ElementCategory.metal),
  ChemicalElement('Chumbo', 6, 14, ElementCategory.metal),
  ChemicalElement('Polônio', 6, 16, ElementCategory.semimetal),
  ChemicalElement('Astato', 6, 17, ElementCategory.nonmetal),
  ChemicalElement('Radônio', 6, 18, ElementCategory.nonmetal),
  ChemicalElement('Frâncio', 7, 1, ElementCategory.metal),
  ChemicalElement('Rádio', 7, 2, ElementCategory.metal),
  [
    ChemicalElement('Actínio', 7, 3, ElementCategory.metal),
    ChemicalElement('Tório', 7, 4, ElementCategory.metal),
    ChemicalElement('Protactínio', 7, 5, ElementCategory.metal),
    ChemicalElement('Urânio', 7, 6, ElementCategory.metal),
    ChemicalElement('Netúnio', 7, 7, ElementCategory.metal),
    ChemicalElement('Plutônio', 7, 8, ElementCategory.metal),
    ChemicalElement('Amerício', 7, 9, ElementCategory.metal),
    ChemicalElement('Cúrio', 7, 10, ElementCategory.metal),
    ChemicalElement('Berquélio', 7, 11, ElementCategory.metal),
    ChemicalElement('Califórnio', 7, 12, ElementCategory.metal),
    ChemicalElement('Einstênio', 7, 13, ElementCategory.metal),
    ChemicalElement('Férmio', 7, 14, ElementCategory.metal),
    ChemicalElement('Mendelévio', 7, 15, ElementCategory.metal),
    ChemicalElement('Nobélio', 7, 16, ElementCategory.metal),
    ChemicalElement('Laurêncio', 7, 17, ElementCategory.metal)
  ],
  ChemicalElement('Rutherfórdio', 7, 4, ElementCategory.metal),
  ChemicalElement('Dúbnio', 7, 5, ElementCategory.metal),
  ChemicalElement('Seabórgio', 7, 6, ElementCategory.metal),
  ChemicalElement('Bóhrio', 7, 7, ElementCategory.metal),
  ChemicalElement('Hássio', 7, 8, ElementCategory.metal),
  ChemicalElement('Meitnério', 7, 9, ElementCategory.metal),
  ChemicalElement('Darmstádio', 7, 10, ElementCategory.metal),
  ChemicalElement('Roentgênio', 7, 11, ElementCategory.metal),
  ChemicalElement('Copernício', 7, 12, ElementCategory.metal),
  ChemicalElement('Nihônio', 7, 13, ElementCategory.metal),
  ChemicalElement('Fleróvio', 7, 14, ElementCategory.metal),
  ChemicalElement('Moscóvio', 7, 15, ElementCategory.metal),
  ChemicalElement('Livermório', 7, 16, ElementCategory.metal),
  ChemicalElement('Tenessino', 7, 17, ElementCategory.nonmetal),
  ChemicalElement('Oganessônio', 7, 18, ElementCategory.nonmetal)
];

List<Widget> elementListWidget = elementList.map((item) {
  if (item is ChemicalElement) {
    return ElementCellWidget(element: item);
  }
  return ElementCellListWidget(elements: item);
}).toList();
