name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.24.1

      - run: flutter build web --wasm
      - run: |
          cat <<EOF > build/web/_headers
          /*
            Cross-Origin-Opener-Policy: same-origin
            Cross-Origin-Embedder-Policy: require-corp
          EOF

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: tabela-periodica
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
